name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run format check
      run: cargo fmt -- --check
    - name: Build release mode
      run: cargo build --release
    - name: Archive the release executable
      uses: actions/upload-artifact@v2
      with:
        name: target/release/aoc2021
        path: aoc2021
